name: 'Kiuwan Baseline Analysis'
author: 'Luis Sanchez'
description: 'Run Kiuwan Baseline analysis on the selected set of code'
inputs:
  project:
    description: 'Name of Kiuwan project'
    required: true
  label:
    description: 'Label of the analysis'
    required: false
    default: ' '

branding:
  color: 'green'
  icon: 'codesandbox'

runs:
  #falta todo esto... puf
