name: 'Kiuwan Baseline Analysis'
author: 'Kiuwan'
description: 'Run Kiuwan Baseline analysis on the repository executing the action'
inputs:
  project:
    description: 'Name of Kiuwan project'
    required: false
    default: ${{ github.repository }}
  label:
    description: 'Label of the analysis'
    required: false
    default: ${{ github.run_number }}
  userid:
    description: 'Username for kiuwan platform'
    required: true
  password:
    description: 'Password for kiuwan platform'
    required: true
  databasetype:
    description: 'Database type files in the project, if any. Can be one or more of [none, transacsql, plsql, informix]'
    required: false
    default: 'none'

outputs:
  result:
    description: 'Return code of the execution of kiuwan'
  analysisurl:
    description: 'URL of the executed analysis'

branding:
  color: 'green'
  icon: 'code'

runs:
  using: 'docker'
  image: 'Dockerfile'
