name: 'Kiuwan Baseline Analysis'
author: 'Kiuwan'
description: 'Run Kiuwan Baseline analysis on the selected set of code'
inputs:
  project:
    description: 'Name of Kiuwan project'
    required: true
  label:
    description: 'Label of the analysis'
    required: false
    default: ' '
  userid:
    description: 'Username for kiuwan platform'
    required: true
  password:
    description: 'Password for kiuwan platform'
    required: true

outputs:
  result:
    description: 'Return code of the execution of kiuwan'

branding:
  color: 'green'
  icon: 'codesandbox'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.project }}
    - ${{ inputs.label }}
    - ${{ inputs.userid }}
    - ${{ inputs.password }}

    
